run:
	g++ -g models/mesh.cpp utilities/controller.cpp source/main.cpp -w -lGL -lGLU -lglut -lglfw -lGLEW -o ./bin/main
	./bin/main
clean:
	rm -f bin/*.o models/*.o models/*.gch models/*~ utilites/*.o utilites/*~
